---
title: "Нано исследование"
output:
  html_document:
    df_print: paged
lang: russian
---
в этом исследовании мы рассмотрим цены на квартиры в Москве.

```{r, include=FALSE}
library("memisc")
library("lmtest")
library("ggplot2")
library("dplyr")
library("foreign")
library("vcd")
library("devtools")
library("hexbin")
library("pander")
library("sjPlot")
library(knitr)
f <- read.csv("flats_moscow.txt", sep="\t", header=TRUE, dec=".")
opts_chunk$set(echo=FALSE, message=FALSE)
```

в нашем наборе данных `r nrow(f)` наблюдений. Средняя цена квартиры равна `r mean(f$price)` тысяе у.е.

Красивый график:
```{r}
f <- mutate_each(f, "factor", walk, brick, floor, code)
qplot(data=f, log(price), fill=brick, position="dodge")
```

Оценим и сравним модели 
```{r, results='asis'}
model_0 <- lm(data=f, log(price)~log(totsp))
model_1 <- lm(data=f, log(price)~log(totsp)+brick)
model_2 <- lm(data=f,log(price)~log(totsp)+brick+brick:log(totsp))
mt <- mtable(model_0, model_1, model_2)
mt
```

У нас оказалась лучше модель 2.
